using ApiClient;
using Application;
using Application.Responses;
using System;
using System.Collections.Generic;
using UIConsole;
using Xunit;

namespace xUnitTest
{
    public class ManagerShould
    {
        // *** Start API first in Package Manager | 'cd FBM.API' | 'dotnet run' ***

        [Fact]
        public async void HaveAName()
        {
            //Fetch the Managers Name

            //Arrange
            string managerName = "Lord Manager";
            ManagerResponse teamManager = await ManagerClient.GetManagerByName(managerName);

            //Act
            string expected = "Lord Manager";
            string? actual = teamManager.Name;

            //Assert
            Assert.Equal(expected, actual);
            //actual = "";
        }

        [Fact]
        public async void HaveATeamWithID()
        {
            //Fetch the Managers Name

            //Arrange
            string managerName = "Lord Manager";
            ManagerResponse teamManager = await ManagerClient.GetManagerByName(managerName);

            //Act
            Guid expected = Guid.Parse("b5d4e653-7e8d-ec11-8465-244bfe57fd18");
            Guid actual = teamManager.ManagingTeamID;

            //Assert
            Assert.Equal(expected, actual);
            //actual = "";
        }

        [Fact]
        public async void HaveATeamNameAssociatedWithID()
        {
            //Fetch the Managers Name

            //Arrange
            string managerName = "Lord Manager";
            ManagerResponse teamManager = await ManagerClient.GetManagerByName(managerName);
            TeamResponse Team = await TeamClient.GetTeamById(teamManager.ManagingTeamID);

            //Act
            string expected = "Manchester United";
            string? actual = Team.TeamName;

            //Assert
            Assert.Equal(expected, actual, ignoreCase: true);
            //actual = "";
        }

        [Fact]
        public async void NotHaveWrongTeamName()
        {
            //Arrange
            Guid managedTeamId = Guid.Parse("b5d4e653-7e8d-ec11-8465-244bfe57fd18");
            TeamResponse managedTeam = await TeamClient.GetTeamById(managedTeamId);

            //Act
            string expected = "Manchester City";
            string? actual = managedTeam.TeamName;

            //Assert
            Assert.NotEqual(expected, actual);
            //}
        }

        [Fact]
        public async void HaveManagerNameIncludeOnlyInternationalAlphaCharsWithCapitalFirsts()
        {
            //Arrange
            //string managerName = "Lord Manager";
            Guid managedTeamId = Guid.Parse("b5d4e653-7e8d-ec11-8465-244bfe57fd18");
            //ManagerResponse teamManager = await ManagerClient.GetManagerByName(managerName);
            TeamResponse managedTeam = await TeamClient.GetTeamById(managedTeamId);

            //Act
            managedTeam.TeamName = "Manchester City";
            string? actual = managedTeam.TeamName;

            //Assert
            Assert.DoesNotMatch("[A-Z[a-z]+ [A-Z[a-z]+", actual);
            //}
        }

        //TODO NotBeInListOfOppositeTeams
        [Fact]
        public async void NotBeInListOfOpposiongTeams()
        {
            //Arrange
            List<TeamResponse> teams = await TeamClient.GetAllTeams();
            var managedTeamId = Guid.NewGuid();
            GetOpposingTeams.GetOppTeams(teams, managedTeamId);

            //Act

            //Assert
        }


        //TODO HaveAName
        //TODO HaveATeam
        //TODO HaveAInitialBankof50000
        //TODO HaveAnInitialScoreOf0

        //TODONTH - HaveADateOfBirth(Autogenerated or input from user)

    }
}
